// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khwxainwmpzzdhunrmtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtod3hhaW53bXB6emRodW5ybXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTAwMDQsImV4cCI6MjA2NDkyNjAwNH0.SUv4_2ypNiuNlS0n4pSH9kDI8s3lK5H9FJiQxef0gtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);